name = "ChowLiuTrees"
uuid = "be466665-d60c-4e0a-9ae9-070eb5e678a5"
authors = ["Guy Van den Broeck <guyvdb@cs.ucla.edu>"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[compat]
CUDA = "3"
julia = "1.6"